### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1095]
As a Bootcamper, I'd like to have a record of my completing the Bootcamp, similar to what I get from completing an xPRO course (see for example: https://xpro-rc.odl.mit.edu/certificate/268d24da-1601-4d80-a065-39aa82e6c810/)

As a Bootcamp admin, I need to customize Bootcamp certificates for each Bootcamp 

### Design

Still in progress. In the meantime, reference the xPRO certificates. 

#### MVP
- [x] #1100 data model for storing certificates data, similar to xPRO
- [x] #1101 CMS Interface for creating / editing certificate template
- [x] #1103 user view
- [x] #1102 add a link to the certificate on the applications dashboard 
- [x] #1104 management command to create certificates for all ~~paid~~ enrolled bootcampers in a bootcamp run

#### Post-MVP
- [ ] #1135 management command to block certificate creation for specified bootcampers
- [x] management command to revoke certificate for specified bootcampers 
- [x] Template allows for a partner institution & logo
- [x] template preview for the CMS author, if possible

**Comment by pdpinch** [comment]
@asadiqbal08 @HamzaIbnFarooq can you check off the boxes that are complete?

**Comment by pdpinch** [comment]
I opened an issue for the last remaining checkbox. We can close this epic.
