### ISSUE TITLE
Remove FLUIDREVIEW_ and SMAPPLY_ fields

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#511]
#### Summary

After PR #500 is deployed

- `FLUIDREVIEW_*` - Delete all
- `SMAPPLY_*` - Delete all

#### Applicable Environments

- [x] Apply configuration to CI after #500 deployed
- [x] Apply configuration to RC after #500 deployed
- [x] Apply configuration to Production after #500 deployed

**Comment by shaidar** [comment]
Deployed to all envs.
