### ISSUE TITLE
Product Page feedback

### ISSUE THREAD

**Issue by odlbot** [mitodl/bootcamp-ecommerce#644]
See the checklist https://trello.com/c/035LQAeT/181-product-page-feedback

┆Attachments: <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/672">bootcamp-ecommerce #672 Product Page Feedback: css changes</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/671">bootcamp-ecommerce #671 Product Page Feedback: style changes</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/674">bootcamp-ecommerce #674 Product page feedback: horizontal scroll on narrow width</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/682">bootcamp-ecommerce #682 Product Page Feedback: minor changes</a> | <a href="https://trello-attachments.s3.amazonaws.com/5e448428fb73a343e4eeac2c/5ee3b3091e95963e44348d35/2b51475b2e89fd0dec88cbf451254c6a/image.png">incorrect letter spacing</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/686">bootcamp-ecommerce #686 Product page feedback: remove CSS that sets letter spacing</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/687">bootcamp-ecommerce #687 Product page feedback: Enable slugs</a> | <a href="https://trello-attachments.s3.amazonaws.com/5e448428fb73a343e4eeac2c/5ee3b3091e95963e44348d35/914f592e5ad6b0a9aaae553b503b4e51/Screenshot_2020-06-19_at_00.10.17.png">Screenshot 2020-06-19 at 00.10.17.png</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/698">bootcamp-ecommerce #698 Product Page Feedback: Accessibility error</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/711">bootcamp-ecommerce #711 Product Page feedback: some section changes</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/713">bootcamp-ecommerce #713 Product Page feedback: The margins between sections should be consistent, and larger</a> | <a href="https://github.com/mitodl/bootcamp-ecommerce/issues/749">bootcamp-ecommerce #749 Product Page feedback: Instructors: line height for instructors&#39; title is too large (almost double-spaced).</a> | <a href="https://trello-attachments.s3.amazonaws.com/5e448428fb73a343e4eeac2c/5ee3b3091e95963e44348d35/c6364caaeb735a1be0ef76398c2ff745/zoom_0.mp4">line-spacing for Instructors is too large</a>

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

If you will work on this:

  1. Select one or more checklist items from Trello
  2. Open an issue in github for the checklist item(s) 
  3. Link the checklist item(s) in Trello to the github issue
  4. When you open a PR in github, be sure to use the "fixes #" command in your PR text. 
  5. When you PR is on RC, please check off the box(es) in Trello.

**Comment by odlbot** [comment]
➤ Umar Asghar commented:

pdpinch could you elaborate that last point? I am asking about "CMS: change "page" to "section" in CMS".

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

I added 8 more checkboxes. I'll list them here, because I'm going to re-sort the checkboxes into priority order. 

  * [ ] Don't capitalize the Bootcamp title ("MIT innovation and Entrepreneurship Bootcamp" on https://bootcamp-rc.odl.mit.edu/bootcamps/bootcamp-14/
  * [ ] Remove the CSS that sets the letter-spacing. We should use the default letter-spacing.
  * [ ] User Benefits: double the right margin (currently appears to be zero)
  * [ ] Program Description Section: instead of numbering the steps, use a > (greater than symbol). Presumably this means changing these steps from an ordered list to an unordered list.

**Comment by odlbot** [comment]
➤ AB commented:

pdpinch is the letter-spacing revert limited to CMS pages? I don't see any CMS SCSS that sets letter spacing :confused:

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

I think the letter-spacing is set here: https://github.com/mitodl/bootcamp-ecommerce/blob/11c862fdf04f1aa72cb6218257bd4bfa0e58a34e/static/scss/_shared.scss#L58

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

I added a screenshot with the letter spacing issue

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

imumar I'm talking about the header text. The header text for all 3 elements should be an H2 (at least, they should be headers and they should not be H1). The font-size should be the same for all three, and it should be the same as the size of the "How to Apply" text, which is 3em.

**Comment by odlbot** [comment]
➤ Umar Asghar commented:

pdpinch this is how it does look like after applying these changes on the Instructor section I can move it a bit toward the right side, but the content on the right side is way more than How to Apply Section and that will ultimately increase our page size vertically.

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

Ok. Let me discuss further with the person who made the request. Maybe I misunderstood them.

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

I added another checkbox, to add the navbar merged in https://github.com/mitodl/bootcamp-ecommerce/pull/688

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

"The margins between sections should be consistent, and larger." => 6 0px

**Comment by odlbot** [comment]
➤ Umar Asghar commented:

pdpinch do we have any clear update on that point? "Instructors" and "Alumni" headers should be the same size (and same element) as the "How to Apply" header.

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

Umar and I discussed and we decided to standardize the headers at 36px.

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

Added a checkbox about the instructor section

**Comment by odlbot** [comment]
➤ Umar Asghar commented:

pdpinch I have a few concerns on "Instructors: line-height for instructors' title is too large (almost double-spaced). Scrollbars aren't good. Can we change overflow to visible, and then rely on the CMS user to make the text fit?"

I am reducing the letter-spacing for now but for the rest, I need your opinion on these 

  * The line-height is normal if we compare it with 36px header
  * There are no scrollbars in it

Could you please confirm it?

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

imumar you can see the effect of the too-large line-spacing at https://bootcamp-rc.odl.mit.edu/bootcamps/healthcare-innovation/ particularly for the instructor Eric von Hippel. I'll attach a screen recording as well.

**Comment by odlbot** [comment]
➤ Umar Asghar commented:

pdpinch I have seen that line-spacing issues will be resolved after ahmed PR https://github.com/mitodl/bootcamp-ecommerce/pull/690.

**Comment by odlbot** [comment]
➤ Umar Asghar commented:

yeah, that video made it clear. I was looking in the header title. thanks and now I am addressing it that what could be done.

**Comment by odlbot** [comment]
➤ Peter Pinch commented:

imumar asadiqbal5 ahmed_arbisoft a couple more styling issues for you
